### PR TITLE
Add base README, CONTRIBUTING, and CODE_OF_CONDUCT files

### PR DESCRIPTION
**Pull request by jhelwig**

### CODE REVIEW

**Comment by jhelwig** [comment]
Definitely welcome suggestions for edits. Wasn't really sure what to put in the `CONTRIBUTING.md` & `README.md`. Also, if there's a different code of conduct template that'd be good, I'd love to hear about it.

**Comment by aeschright** [comment]
Maybe the contributing doc should explain a little about the setup and which parts are the Calagator gem vs this repo? I don't know what contributions besides design we might expect though.

**Comment by jhelwig** [comment]
Yeah, I'd be very surprised if there was anything other than design/typo type stuff. Pretty much everything of substance would be against the Calagator gem. :\

**Comment by jhelwig** [comment]
I'm thinking we should merge this now, and add clarifications to the contributing doc about what goes in this repo vs. in the Calagator gem as the questions come up, rather than guessing at what questions there might be. Sound reasonable, @aeschright?

**Review by aeschright — APPROVED** [review]
Sounds good.

**Pull request merged**
